pipeline {
    agent any
    environment {
        DOCKER_USER = "ahmed1399"
        DOCKER_IMAGE_NAME = 'simple-image'
        DOCKER_IMAGE_TAG = "${BUILD_NUMBER}"
        DOCKER_CREDENTIALS_ID = 'docker-hub-cred'
    }
    stages {
        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }
        stage('Checkout Code') {
            steps {
                script {
                    // Checkout the code into the 'Jenkins' directory
                    checkout scm: [
                        $class: 'GitSCM',
                        branches: [[name: '*/main']],  // Specify the branch name (main)
                        doGenerateSubmoduleConfigurations: false,
                        userRemoteConfigs: [
                            [url: 'https://github.com/Ahmed-1399/Jenkins.git', credentialsId: 'github_cred']
                        ]
                    ]
                }    
            }
        }        
        stage('Navigate to Task1') {
            steps {
                // Navigate to {Task1} that contains {Jenkinsfile}
                dir('Task1') {
                    echo "Switched to Task1 directory"
                    sh 'pwd'
                    sh 'ls'
                }
            }
        }
        stage('Credentials for Docker Hub') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'docker-hub-cred',
                                    usernameVariable: 'DOCKER_USER',  
                                    passwordVariable: 'DOCKER_PASS')]) {
                        sh '''
                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                        '''
                    }
                }
            }
        }
        stage('Build & Tag Docker Image') {
            steps {
                script {
                    // Specify Path of {Dockerfile}
                    sh '''
                    if [ -f Task1/Dockerfile ]; then
                        docker build -f Task1/Dockerfile -t ${DOCKER_USER}/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG} .
                    else
                        echo "ERROR: Dockerfile not found!"
                        exit 1
                    fi
                    '''
                }
            }
        }
        stage('Push Docker Image') {
            steps {
                script {
                    sh "docker push ${DOCKER_USER}/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}"
                }
            }
        }
        stage('Run Docker Container') {
            steps {
                // Remove {Old Container} to Run {New Container}
                sh "docker rm -f test_con || true"
                sh "docker run -d --name test_con -p 3030:80 ${DOCKER_USER}/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}"
            }
        }
    }
    post {
        success {
            echo 'Docker image built and pushed successfully!'
        }
        failure {
            echo 'Pipeline failed! Check the logs for details.'
        }
    }
}